### ISSUE TITLE
Create slides with instructions for hackathon participants

### ISSUE THREAD

**Issue by jeff-cohere** [NCAR/aerosol-workshop-driver#25]
We need a slide deck with some high-level ideas:

* circles and arrows identifying host and aerosol models and how they communicate
* basic data structures and their roles
* an animated walkthrough of what the driver does and the data structures it uses
* a cheat sheet with terminology and API essentials
* ???

**Comment by bnmurphy** [comment]
Consider also...
- a clear description or bulleted list of what a successful aerosol package implementation achieves. Maybe a brief guide on how to start with the reference (i.e. stub) aerosol package and add to it. If possible add some basic guidance or do's and don'ts.
- a summary of the test cases we've defined, acknowledgement that the participant must transform these general data into input data compatible with their package, and an expectation of the model output. 
- we can consider defining figure axes or an output format for the minimum data that will be shared back with the group at the end? Of course participants can share more or more-complicated results as well if they have a more complex package.

**Comment by jeff-cohere** [comment]
The slides I put together today explain a good deal of the original set of items. I think because we're pressed for time (and because it's easier to field questions in a live setting) I'm going to do a "code tour" that summarizes the points that @bnmurphy added. As for what gets reported back at the end of the hackathon, we should raise that as a question for the organizing committee.
