### ISSUE TITLE
Open questions

### ISSUE THREAD

**Issue by jeff-cohere** [NCAR/aerosol-workshop-driver#32]
1. Do we compute optical properties on grid interfaces or midpoints? **CAM computes on grid interfaces, so maybe let's do that.**
2. Does our linear interpolator recover linear and piecewise linear functions exactly?

**Comment by mattldawson** [comment]
2. Check interpolator logic

**Comment by mattldawson** [comment]
I think from a quick look at the CAM code that the optical properties are all at interfaces, and I think they are using the same wavelength grid in the aerosol code as is used in radiation, so there is no interpolation
